CREATE TABLE IF NOT EXISTS silver_vehicle_specs (
    make text,
    model text,
    year integer,
    fuel_type text,
    engine_cylinders integer,
    engine_size_l double precision,
    drivetrain text,
    transmission text,
    city_efficiency double precision,
    highway_efficiency double precision,
    combined_efficiency double precision,
    co2_emissions_g_per_mile double precision,
    ev_range_miles double precision,
    vehicle_category text,
    ingested_at timestamptz,
    source_file text,
    batch_id text,
    is_ev boolean,
    is_ice boolean,
    is_hybrid_or_other boolean,
    efficiency_unit text,
    is_valid_year boolean,
    is_valid_ev_range boolean,
    is_valid_engine_for_ev boolean,
    is_valid_emissions_for_ev boolean,
    has_missing_required_fields boolean,
    is_valid_combined_efficiency boolean
);
